# Generated by Django 6.1 on 2026-08-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_text', models.TextField(blank=True, default='')),
                ('peril', models.CharField(blank=True, default='', max_length=50)),
                ('zone', models.CharField(blank=True, default='', max_length=100)),
                ('loss_lo', models.FloatField(default=0.0)),
                ('loss_hi', models.FloatField(default=300.0)),
                ('filter_mode', models.CharField(default='Industry Loss', max_length=30)),
                ('event_keyword', models.CharField(blank=True, default='', max_length=200)),
                ('low_event_id', models.IntegerField(default=0)),
                ('med_event_id', models.IntegerField(default=0)),
                ('high_event_id', models.IntegerField(default=0)),
                ('database', models.CharField(blank=True, default='', max_length=100)),
                ('candidate_event_ids', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
