MODEL_CATALOG = {
    5:  {"industry_peril": "FI",   "region": "US",              "label": "US Wildfire"},
    6:  {"industry_peril": None,   "region": "AusNZ",           "label": "Australia Bushfire"},
    8:  {"industry_peril": None,   "region": "US",              "label": "US Flood"},
    10: {"industry_peril": None,   "region": "SouthAfrica",     "label": "South Africa Earthquake"},
    11: {"industry_peril": "EQ",   "region": "US/Canada",       "label": "US/Canada Earthquake"},
    13: {"industry_peril": "EQ",   "region": "US",              "label": "Hawaii Earthquake"},
    14: {"industry_peril": "EQ",   "region": "US",              "label": "Alaska Earthquake"},
    15: {"industry_peril": "EQ",   "region": "Caribbean",       "label": "Caribbean Earthquake"},
    18: {"industry_peril": None,   "region": "Asia",            "label": "Japan Flood"},
    19: {"industry_peril": None,   "region": "Canada",          "label": "Canada Flood"},
    22: {"industry_peril": None,   "region": "US",              "label": "US Severe Thunderstorm"},
    23: {"industry_peril": "TC",   "region": "US",              "label": "Hawaii Hurricane"},
    26: {"industry_peril": None,   "region": "Canada",          "label": "Canada Severe Storm"},
    27: {"industry_peril": "TC",   "region": "US/Caribbean",    "label": "North Atlantic Hurricane"},
    28: {"industry_peril": "WS",   "region": "US",              "label": "US Winter Storm"},
    30: {"industry_peril": None,   "region": "Canada",          "label": "Canada Hurricane"},
    31: {"industry_peril": "EQ",   "region": "Europe/MidEast",  "label": "Europe/Mid East Earthquake"},
    33: {"industry_peril": None,   "region": "Europe",          "label": "SE Europe Earthquake"},
    36: {"industry_peril": None,   "region": "Asia",            "label": "India Flood"},
    37: {"industry_peril": None,   "region": "AusNZ",           "label": "Australia Wildfire"},
    38: {"industry_peril": None,   "region": "Canada",          "label": "Canada Windstorm"},
    39: {"industry_peril": None,   "region": "AusNZ",           "label": "Australia Severe Storm"},
    40: {"industry_peril": None,   "region": "US",              "label": "Guam Earthquake"},
    41: {"industry_peril": "WS",   "region": "Europe",          "label": "Europe Winter Storm"},
    42: {"industry_peril": None,   "region": "Canada",          "label": "Canada Winter Storm"},
    43: {"industry_peril": None,   "region": "Europe",          "label": "Europe Severe Storm"},
    44: {"industry_peril": None,   "region": "AusNZ",           "label": "Australia Severe Thunderstorm"},
    47: {"industry_peril": None,   "region": "SouthAfrica",     "label": "South Africa Severe Storm"},
    48: {"industry_peril": None,   "region": "Other",           "label": "Other Severe Storm"},
    50: {"industry_peril": None,   "region": "MidEast",         "label": "Middle East Earthquake"},
    51: {"industry_peril": "EQ",   "region": "AusNZ",           "label": "Australia Earthquake"},
    52: {"industry_peril": "EQ",   "region": "Asia",            "label": "Japan Earthquake"},
    53: {"industry_peril": "EQ",   "region": "AusNZ",           "label": "New Zealand Earthquake"},
    54: {"industry_peril": "EQ",   "region": "Asia",            "label": "SE Asia Earthquake"},
    55: {"industry_peril": "EQ",   "region": "Asia",            "label": "China Earthquake"},
    58: {"industry_peril": None,   "region": "Asia",            "label": "India Earthquake"},
    59: {"industry_peril": None,   "region": "AusNZ",           "label": "Australia Flood"},
    60: {"industry_peril": "ST+WD","region": "Asia",            "label": "NW Pacific Typhoon"},
    61: {"industry_peril": "TC",   "region": "AusNZ",           "label": "Australia Tropical Cyclone"},
    64: {"industry_peril": None,   "region": "Other",           "label": "Other Earthquake"},
    66: {"industry_peril": None,   "region": "Other",           "label": "Other Fire"},
    67: {"industry_peril": None,   "region": "Other",           "label": "Other"},
    68: {"industry_peril": None,   "region": "Asia",            "label": "India Cyclone"},
    70: {"industry_peril": "EQ",   "region": "SouthAmerica",    "label": "South America Earthquake"},
    72: {"industry_peril": "EQ",   "region": "CentralAmerica",  "label": "Mexico Earthquake"},
    76: {"industry_peril": "EQ",   "region": "CentralAmerica",  "label": "Central America Earthquake"},
    78: {"industry_peril": None,   "region": "Asia",            "label": "South Korea Earthquake"},
    79: {"industry_peril": None,   "region": "Canada",          "label": "Canada Wildfire"},
    90: {"industry_peril": None,   "region": "Europe",          "label": "Central Europe Flood"},
    92: {"industry_peril": None,   "region": "Europe",          "label": "UK Flood"},
    94: {"industry_peril": None,   "region": "Europe",          "label": "SE Europe Flood"},
    96: {"industry_peril": None,   "region": "Europe",          "label": "Italy Flood"},
    97: {"industry_peril": None,   "region": "Other",           "label": "Other Flood"},
    98: {"industry_peril": None,   "region": "Europe",          "label": "Belgium Flood"},
    99: {"industry_peril": None,   "region": "Asia",            "label": "SE Asia Flood"},
}

PERIL_DB_CODES = {
    "EQ":                ["EQ"],
    "TC":                ["TC", "ST+WD"],
    "Winter Storm":      ["WS"],
    "Severe Storm":      ["ST"],
    "Fire / Wildfire":   ["FI"],
}

_PERIL_TO_MODELS = {
    "EQ":              [10, 11, 13, 14, 15, 31, 33, 40, 50, 51, 52, 53, 54, 55, 58, 64, 70, 72, 76, 78],
    "TC":              [23, 27, 30, 60, 61, 68],
    "Winter Storm":    [28, 38, 41, 42],
    "Severe Storm":    [22, 26, 39, 43, 44, 47, 48],
    "Fire / Wildfire": [5, 6, 37, 66, 79],
    "Flood":           [8, 18, 19, 36, 59, 90, 92, 94, 96, 97, 98, 99],
}

PERIL_ALIASES = {
    "eq": "EQ", "earthquake": "EQ", "quake": "EQ", "seismic": "EQ",
    "hurricane": "TC", "typhoon": "TC", "cyclone": "TC",
    "tropical": "TC", "tc": "TC",
    "wind": "TC", "storm": "Severe Storm",
    "winterstorm": "Winter Storm", "winter storm": "Winter Storm",
    "winter": "Winter Storm", "ws": "Winter Storm",
    "severe thunderstorm": "Severe Storm", "thunderstorm": "Severe Storm",
    "tornado": "Severe Storm", "hail": "Severe Storm",
    "convective": "Severe Storm", "st": "Severe Storm",
    "flood": "Flood", "flooding": "Flood", "inland flood": "Flood",
    "wildfire": "Fire / Wildfire", "fire": "Fire / Wildfire",
    "bushfire": "Fire / Wildfire", "fi": "Fire / Wildfire",
}

ZONE_TOKEN_MAP = {
    "us": "US", "usa": "US", "u.s.": "US",
    "unitedstates": "US", "united states": "US", "america": "US",
    "florida": "Zone 03 FL", "fl": "Zone 03 FL", "miami": "Zone 03 FL",
    "california": "Zone 08", "ca": "Zone 08",
    "los angeles": "Zone 08", "san francisco": "Zone 08", "san diego": "Zone 08",
    "texas": "Zone 03 Gulf", "tx": "Zone 03 Gulf",
    "gulf": "Zone 03 Gulf", "gulfcoast": "Zone 03 Gulf",
    "georgia": "Zone 03 GA SC", "ga": "Zone 03 GA SC",
    "south carolina": "Zone 03 GA SC", "sc": "Zone 03 GA SC",
    "north carolina": "Zone 03 NC", "nc": "Zone 03 NC",
    "northeast": "Zone 01", "new england": "Zone 01",
    "midatlantic": "Zone 02", "mid atlantic": "Zone 02",
    "southeast": "Zone 04", "se": "Zone 04",
    "midwest": "Zone 05 and 06", "central": "Zone 05 and 06",
    "northwest": "Zone 07", "pacific northwest": "Zone 07",
    "west": "Zone 08", "mountain": "Zone 08",
    "alaska": "Zone 09", "ak": "Zone 09",
    "hawaii": "Zone 10", "hi": "Zone 10",
    "ny": "Zone 01", "nj": "Zone 02", "pa": "Zone 02",
    "ct": "Zone 01", "ma": "Zone 01", "ri": "Zone 01",
    "nh": "Zone 01", "vt": "Zone 01", "me": "Zone 01",
    "md": "Zone 02", "va": "Zone 04", "de": "Zone 02",
    "la": "Zone 03 Gulf", "ms": "Zone 03 Gulf", "al": "Zone 04",
    "wa": "Zone 07", "or": "Zone 07",
    "az": "Zone 08", "nm": "Zone 08", "co": "Zone 08",
    "ut": "Zone 08", "nv": "Zone 08",
    "mn": "Zone 05 and 06", "wi": "Zone 05 and 06",
    "il": "Zone 05 and 06", "in": "Zone 05 and 06",
    "mi": "Zone 05 and 06", "oh": "Zone 05 and 06",
    "mo": "Zone 05 and 06", "ia": "Zone 05 and 06",
    "ks": "Zone 05 and 06", "ne": "Zone 05 and 06",
    "ok": "Zone 04", "ar": "Zone 04",
    "ky": "Zone 04", "tn": "Zone 04", "wv": "Zone 04",
    "nd": "Zone 05 and 06", "sd": "Zone 05 and 06",
    "mt": "Zone 07", "wy": "Zone 08", "id": "Zone 07",
    "caribbean": "Caribbean", "puerto rico": "Caribbean  Puerto Rico",
    "bahamas": "Caribbean  Bahamas", "bermuda": "Caribbean  Bermuda",
    "jamaica": "Caribbean  Jamaica", "cuba": "Caribbean  Cuba",
    "dominican republic": "Caribbean  Dominican Republic",
    "trinidad": "Caribbean  Trinidad and Tobago",
    "virgin islands": "Caribbean  Virgin Islands",
    "cayman": "Caribbean  Cayman Islands",
    "canada": "Canada", "canadian": "Canada",
    "ontario": "Canada  ON", "on": "Canada  ON",
    "quebec": "Canada  QC", "qc": "Canada  QC",
    "bc": "Canada  BC", "british columbia": "Canada  BC",
    "alberta": "Canada  AB", "ab": "Canada  AB",
    "mexico": "Central America  Mexico", "mexican": "Central America  Mexico",
    "costa rica": "Central America  Costa Rica",
    "guatemala": "Central America  Guatemala",
    "panama": "Central America  Panama",
    "honduras": "Central America  Honduras",
    "el salvador": "Central America  El Salvador",
    "nicaragua": "Central America  Nicaragua",
    "belize": "Central America  Belize",
    "central america": "Central America",
    "venezuela": "South America  Venezuela", "venezuelan": "South America  Venezuela",
    "colombia": "South America  Colombia", "colombian": "South America  Colombia",
    "peru": "South America  Peru", "peruvian": "South America  Peru",
    "ecuador": "South America  Ecuador", "ecuadorian": "South America  Ecuador",
    "chile": "South America  Chile", "chilean": "South America  Chile",
    "south america": "South America",
    "europe": "Europe", "european": "Europe",
    "uk": "Europe  UK", "united kingdom": "Europe  UK",
    "britain": "Europe  UK", "england": "Europe  UK",
    "germany": "Europe  Germany", "german": "Europe  Germany",
    "france": "Europe  France", "french": "Europe  France",
    "italy": "Europe  Italy", "italian": "Europe  Italy",
    "spain": "Europe  Spain", "spanish": "Europe  Spain",
    "netherlands": "Europe  Netherlands", "dutch": "Europe  Netherlands",
    "switzerland": "Europe  Switzerland", "swiss": "Europe  Switzerland",
    "ireland": "Europe  Ireland", "irish": "Europe  Ireland",
    "poland": "Europe  Poland",
    "denmark": "Europe  Denmark",
    "norway": "Europe  Norway",
    "sweden": "Europe  Sweden",
    "finland": "Europe  Finland",
    "austria": "Europe  Austria",
    "belgium": "Europe  Belgium",
    "portugal": "Europe  Portugal",
    "greece": "Europe  Greece",
    "czech": "Europe  Czech Republic",
    "romania": "Europe  Romania",
    "asia": "Asia", "asian": "Asia",
    "japan": "Asia  Japan", "japanese": "Asia  Japan",
    "china": "Asia  China", "chinese": "Asia  China",
    "taiwan": "Asia  Taiwan",
    "philippines": "Asia  Philippines", "filipino": "Asia  Philippines",
    "indonesia": "Asia  Indonesia", "indonesian": "Asia  Indonesia",
    "vietnam": "Asia  Vietnam",
    "south korea": "Asia  South Korea", "korea": "Asia  South Korea",
    "singapore": "Asia  Singapore",
    "hong kong": "Asia  Hong Kong",
    "turkey": "Mid East  Turkey", "turkish": "Mid East  Turkey",
    "turkiye": "Mid East  Turkey",
    "israel": "Mid East  Israel", "israeli": "Mid East  Israel",
    "iran": "Mid East", "iranian": "Mid East",
    "middle east": "Mid East", "mideast": "Mid East",
    "australia": "AusNZ  Australia", "australian": "AusNZ  Australia",
    "new zealand": "AusNZ  New Zealand", "nz": "AusNZ  New Zealand",
    "ausnz": "AusNZ",
    "india": "Asia", "indian": "Asia",
}

QUERY_STOPWORDS = {
    "and", "or", "the", "a", "an", "for", "of", "in", "on", "to",
    "industry", "loss", "range", "event", "description", "keyword", "model",
    "with", "from",
}

STATE_TOKENS = {
    "ny", "tx", "ma", "ct", "pa", "nj", "ca", "fl", "la", "ms", "al", "ga",
    "nc", "sc", "va", "md", "ri", "nh", "vt", "me", "wa", "or", "az", "nm",
    "co", "ut", "nv", "id", "mt", "wy", "nd", "sd", "ne", "ks", "ok", "mo",
    "ia", "mn", "wi", "il", "in", "mi", "oh", "ky", "tn", "ar", "wv", "de",
}

AMBIGUOUS_SHORT_TOKENS = {"in", "or", "me", "de", "on", "hi", "id", "ok", "se"}

PERIL_OPTIONS = ["All", "EQ", "TC", "Winter Storm", "Severe Storm", "Fire / Wildfire", "Flood"]

DESIGN_TOKENS = {
    "everest_blue": "#235CF4",
    "mid_blue": "#0A3699",
    "dark_blue": "#061C49",
    "mid_gray": "#A4ABC8",
    "light_gray": "#F5F5F5",
    "border_gray": "#E2E8F0",
    "scenario_colors": {
        "Low": "#198038",
        "Med": "#E67E22",
        "High": "#DA1E28",
    },
}
